import dotenv from 'dotenv';

dotenv.config();

const {
    ENV,
    PORT,
    URL,
    DB_DRIVER,
    HOST_DEV,
    DB_DEV,
    USER_DEV,
    PASSWORD_DEV,
    HOST_TEST,
    DB_TEST,
    USER_TEST,
    PASSWORD_TEST,
    HOST_PROD,
    DB_PROD,
    USER_PROD,
    PASSWORD_PROD,
    BCRYPT_PASSWORD,
    SALT_ROUNDS,
    TOKEN_SECRET,
} = process.env;

export default {
    env: ENV,
    port: PORT,
    url: URL,
    fullUrl: URL + ':',
    srvrStr: 'Server started at ',
    dbDriver: DB_DRIVER,
    host_Dev: HOST_DEV,
    db_Dev: DB_DEV,
    user_Dev: USER_DEV,
    password_Dev: PASSWORD_DEV,
    host_Test: HOST_TEST,
    db_Test: DB_TEST,
    user_Test: USER_TEST,
    password_Test: PASSWORD_TEST,
    host_Prod: HOST_PROD,
    db_Prod: DB_PROD,
    user_Prod: USER_PROD,
    password_Prod: PASSWORD_PROD,
    pepper: BCRYPT_PASSWORD,
    saltRounds: SALT_ROUNDS,
    tokenSecret: TOKEN_SECRET,
    msgFailError: '. Error: ',
    msgFailGtItm: 'Could not get items. Error: ',
    msgFailFdItm: 'Could not find item ',
    msgFailAdItm: 'Could not add new item ',
    msgFailUpItm: 'Could not update the item ',
    msgFailDtItm: 'Could not delete item ',
    msgFailTrnct: 'Could not truncate items. Error: ',
    msgFailAdPdt: 'Could not add product ',
    msgFailTord: ' to order ',
    msgFailFdPdt: 'Could not find products of order ',
    msgShudHvIdx: 'should have an index method',
    msgShudHvShw: 'should have a show method',
    msgShudHvCrt: 'should have a create method',
    msgShudHvUpd: 'should have an update method',
    msgShudHvDel: 'should have a delete method',
    msgShudHvAdp: 'should have Add Product method',
    msgShudHvShp: 'should have Show Products method',
    msgShudHvGt5: 'should have Get Top 5 Products method',
    msgShudHvGtg: 'should have Get Products By Category method',
    msgShudHvAcu: 'should have Get Active Order By User method',
    msgShudHvCcu: 'should have Get Completed Orders By User method',
    msgShudAdItm: 'create method should add an item',
    msgShudRtLst: 'index method should return a list of items',
    msgShudRtItm: 'show method should return the correct item',
    msgShudEdItm: 'update method should edit an item',
    msgShudDtItm: 'delete method should remove an item',
    msgShudAuthP: 'authenticate method should pass valid credentials',
    msgShudAuthB: 'authenticate method should block invalid credentials',
    msgShudRtPdt: 'Add Product method should return the correct order products',
    msgInvldTkn: 'Invalid Token. ',
    msgUnkwnTkn: 'Unknown Token Type',
    msgInvldUsr: 'Invalid User',
};
